### ISSUE TITLE
plugins.cordova.io will be deprecated in the near future

### ISSUE THREAD

**Issue by bau720123** [Sharinglabs/cordova-plugin-cache#1]
according to this
http://phonegap.com/blog/2015/05/26/npm-plugins-available/
http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

so...just want to inform you that your plugin should be move to npm in the future...

**Comment by devteamshippeo** [comment]
possible to migrate on npmjs.org repository ?

**Comment by bau720123** [comment]
just like @devteamshippeo said

**Comment by devteamshippeo** [comment]
This plugin https://github.com/tiltshiftfocus/cordova-plugin-cache is exposed on NPM via https://www.npmjs.com/package/cordova-plugin-cache

It seems to be the same plugin as Sharinglabs'one (see historic for details)

**Comment by Heshyo** [comment]
This repo was based on https://github.com/moderna/cordova-plugin-cache . The owner never published it on Phonegap Build even after we asked, so we decided to fork it and modify what's necessary to be able to publish it on PGB.

If https://github.com/tiltshiftfocus/cordova-plugin-cache is on NPM, then sure you can use it instead.It'd be best to avoid having duplicated plugins.

**Comment by bau720123** [comment]
thanks @devteamshippeo and @Heshyo 
I will use
https://www.npmjs.com/package/cordova-plugin-cache
to instead the original one

**Comment by bau720123** [comment]
hi @Heshyo 
just want to ask you a simple question
according to this
https://www.npmjs.com/package/cordova-plugin-cache
did you know...
what the detail difference between the "window.cache.clear" and "window.cache.cleartemp"
it look like all doing the "Clear Cache or Temp" thing

if I misunderstood
please correct me
thanks

**Comment by Heshyo** [comment]
@bau720123 
https://github.com/tiltshiftfocus/cordova-plugin-cache/blob/master/src/ios/Cache.m
Looks like for iOS `clear` clears the cache, while `cleartemp` clears the temp folders. The `cleartemp` was added by tiltshiftfocus on his repository and isn't in the original repo.

**Comment by bau720123** [comment]
got it
thanks @Heshyo
