### ISSUE TITLE
PhoneGap Build error in iOS

### ISSUE THREAD

**Issue by stileinverso** [Sharinglabs/cordova-plugin-cache#4]
Hi!
I'm using your plugin in my app that I compile through PhoneGapBuild.
The Android version compiles properly but the **iOS version** give me this error:

**Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: com.tiltshiftfocus.cordova.plugin.clearCache**

Here the string I use in the config.xml file to include your plugin in my app:

```
<plugin name="cordova-plugin-cache" source="npm" />
```

Where am I doing wrong?

**Comment by bau720123** [comment]
hi @stileinverso 
the "cordova-plugin-cache" plugin is another author's plugin (forked from Sharinglabs/cordova-plugin-cache)
https://www.npmjs.com/package/cordova-plugin-cache
https://github.com/tiltshiftfocus/cordova-plugin-cache

so...maybe you should ask "tiltshiftfocus" first

**Comment by stileinverso** [comment]
I'm sorry!
I was convinced of being on the correct page.

**Comment by stileinverso** [comment]
When I go in their GitHub page (https://github.com/tiltshiftfocus/cordova-plugin-cache) and I click the button **New pull request** in **Pull requests** tab (there is no **Issues** tab) the system bring me in your page!
Is it normal?

**Comment by stileinverso** [comment]
Sorry again for the inconvenience.
**I would like to know if your plugin also destroys the local database or not.**
I recommend you to specify also in the the main page/description of the plugin itself.
Thank you.

**Comment by adamnorbacker** [comment]
it still happens.
it just wont compile for ios.
I need it because I get data from server.

In phonegap config.xml:
  `<plugin name="cordova-plugin-cache-npm" version="*" />`
same with:
`<plugin name="cordova-plugin-cache-npm" version="*" />`

**Comment by Heshyo** [comment]
As written previously, `cordova-plugin-cache-npm` is not this plugin.
